#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# 1   Listens on port 80.
# 2   Returns a page containing "Holberton School" when queried
# 3   at the root with a curl GET request.
# 4   Configures /redirect_me as a "301 Moved Permanently".
# 5   Includes a custom 404 page containing "Ceci n'est pas une page".
# 6   Contains a custom HTTP header named X-Served-By.
# 7   The value of the HTTP header is the hostname of the running server.

sudo apt-get update
sudo apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
sudo echo "Holberton School" > /var/www/html/index.html
sudo touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
